http://localhost:5000/api/v1/contact

http://localhost:5000/api/v1/contact/1

# Post
POST http://localhost:5000/api/v1/contact
Content-Type: application/json

{
    "nombre":"Veronica",
    "email":"keyn@dominio.com",
    "mensaje":"Primer Post"
}

PUT http://localhost:5000/api/v1/contact/1
Content-Type: application/json

{
    "id": 1,
    "nombre":"Samuel Alcaraz",
    "email":"sam_zerox@dominio2.com",
    "mensaje":"Primer Post"
}

DELETE http://localhost:5000/api/v1/contact/2




# Login
POST http://localhost:5000/api/v1/login HTTP/1.1
Content-Type: application/json

{
    "username":"samuel",
    "password":"password",
    "email":"samu@dominio.com",
    "fechacreado":"2000-10-31"
}

# Get con Autorizacion
http://localhost:5000/api/v1/contact/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NTY5OTMxNjIsImlzcyI6IkRFQlNDb25zdWx0b3Jlcy5jb20iLCJhdWQiOiJERUJTQ29uc3VsdG9yZXMuY29tIn0.wu68VyUXIDhOeUFsO1fUZeoqgXoiShl1mppuMnow9WI

# Post con Autorizacion
POST http://localhost:5000/api/v1/contact
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2ZXJvbmljYSIsImVtYWlsIjoidmVyb0Bkb21pbmlvLmNvbSIsIkZlY2hhQ3JlYWRvIjoiMjAwMC0xMC0zMSIsImp0aSI6Ijg1YTg2NGI5LTMzMjEtNGZlMy05NGJlLTkzOTkyMDdkOGMzNiIsImV4cCI6MTU1NzA3OTkyNiwiaXNzIjoiREVCU0NvbnN1bHRvcmVzLmNvbSIsImF1ZCI6IkRFQlNDb25zdWx0b3Jlcy5jb20ifQ.-nDygbQW7G0qi9kDN-REqRAOS-o-sDNz6qM0dkGG0gw

{
    "nombre":"Bridgetthe",
    "email":"leah@dominio.com",
    "nace":"2014-02-20T00:00:00",
    "mensaje":"Desde VSC"
}


POST http://localhost:5000/api/v1/login
Content-Type: application/json

{
    "username":"veronica",
    "password":"123456",
}


http://localhost:5000/api/v1/contact
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2ZXJvbmljYSIsImVtYWlsIjoidmVyb0Bkb21pbmlvLmNvbSIsIkZlY2hhQ3JlYWRvIjoiMjAwMC0xMC0zMSIsImp0aSI6Ijg1YTg2NGI5LTMzMjEtNGZlMy05NGJlLTkzOTkyMDdkOGMzNiIsImV4cCI6MTU1NzA3OTkyNiwiaXNzIjoiREVCU0NvbnN1bHRvcmVzLmNvbSIsImF1ZCI6IkRFQlNDb25zdWx0b3Jlcy5jb20ifQ.-nDygbQW7G0qi9kDN-REqRAOS-o-sDNz6qM0dkGG0gw

POST http://localhost:5000/api/v1/login/register/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2ZXJvbmljYSIsImVtYWlsIjoidmVyb0Bkb21pbmlvLmNvbSIsIkZlY2hhQ3JlYWRvIjoiMjAwMC0xMC0zMSIsImp0aSI6Ijg1YTg2NGI5LTMzMjEtNGZlMy05NGJlLTkzOTkyMDdkOGMzNiIsImV4cCI6MTU1NzA3OTkyNiwiaXNzIjoiREVCU0NvbnN1bHRvcmVzLmNvbSIsImF1ZCI6IkRFQlNDb25zdWx0b3Jlcy5jb20ifQ.-nDygbQW7G0qi9kDN-REqRAOS-o-sDNz6qM0dkGG0gw

{
    "username":"samzerox",
    "password":"123456",
    "email":"sam@dominio.com",
    "fechacreado":"2019-05-05"
}